### ISSUE TITLE
[Question] How would I remove a slot

### ISSUE THREAD

**Issue by OfficialRDB** [HarithMichael/lj-inventory-withdecay#2]
Love the integration & the share.

How would I remove slot 6 in the hotbar ?
Is the decay days like IRL days or in-game days ?
What if I don't want a item to decay, am I just using the  ["created"] = nil  or nothing at all?

**Comment by Aero-Codes** [comment]
yea just put ["created"] = nil and don't put the decay if you don't want the item will decay
